import { z } from '@hono/zod-openapi'

/**
 * Shared Zod schemas — single source of truth for request validation and
 * OpenAPI response documentation. Reusable on the client for form validation.
 */

// ---------------------------------------------------------------- primitives
export const UuidSchema = z.uuid().openapi({ example: '123e4567-e89b-12d3-a456-426614174000' })
export const TimestampSchema = z.string().openapi({ format: 'date-time', example: '2026-09-12T08:30:00.000Z' })

export const MoodSchema = z.enum(['great', 'good', 'okay', 'low', 'rough']).openapi({
  description: 'Mood rating: great 😄, good 🙂, okay 😐, low 🙁, rough 😣',
  example: 'good',
})

export const TagsSchema = z
  .array(z.string().min(1).max(40))
  .max(20)
  .openapi({ example: ['gratitude', 'work'], description: 'Free-text tags, per user' })

// ---------------------------------------------------------------- pagination
export const PageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1).openapi({ example: 1, description: '1-based page number' }),
  limit: z.coerce.number().int().min(1).max(100).default(20).openapi({ example: 20 }),
})

export function PaginatedSchema<T extends z.ZodType>(item: T) {
  return z.object({
    data: z.array(item),
    pagination: z.object({
      page: z.number().int().openapi({ example: 1 }),
      limit: z.number().int().openapi({ example: 20 }),
      total: z.number().int().openapi({ example: 42, description: 'Total rows matching the query' }),
    }),
  })
}

// ---------------------------------------------------------------- profiles
export const ProfileSchema = z
  .object({
    id: UuidSchema,
    display_name: z.string().openapi({ example: 'Alex Chen' }),
    email: z.string().openapi({ example: 'alex@example.com', description: 'From the auth user record' }),
    created_at: TimestampSchema,
  })
  .openapi('Profile')

export const UpdateProfileSchema = z
  .object({
    display_name: z.string().min(1).max(80).openapi({ example: 'Alex Chen' }),
  })
  .strict()

// ---------------------------------------------------------------- auth
export const SignUpSchema = z
  .object({
    email: z.email().openapi({ example: 'alex@example.com' }),
    password: z.string().min(8).max(72).openapi({ example: 'correct horse battery', minLength: 8 }),
    display_name: z.string().min(1).max(80).optional().openapi({ example: 'Alex Chen' }),
  })
  .strict()

export const LoginSchema = z
  .object({
    email: z.email().openapi({ example: 'alex@example.com' }),
    password: z.string().min(1).openapi({ example: 'correct horse battery' }),
  })
  .strict()

export const MagicLinkSchema = z
  .object({
    email: z.email().openapi({ example: 'alex@example.com' }),
    redirect_to: z.string().url().optional().openapi({ example: 'http://localhost:3000/auth/callback' }),
  })
  .strict()

export const OAuthStartSchema = z
  .object({
    provider: z
      .enum(['google'])
      .openapi({ example: 'google', description: 'OAuth provider enabled on this deployment' }),
    code_challenge: z.string().min(43).max(128).openapi({
      description: 'Base64url(SHA-256(code_verifier)) — PKCE S256 challenge generated by the client',
      example: 'dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk',
    }),
  })
  .strict()

export const OAuthCallbackSchema = z
  .object({
    auth_code: z
      .string()
      .min(1)
      .max(1024)
      .openapi({ description: 'The code Supabase appended to your redirect URL after the provider round-trip' }),
    code_verifier: z
      .string()
      .min(43)
      .max(128)
      .openapi({ description: 'The PKCE verifier the client stored when starting the flow' }),
  })
  .strict()

export const RefreshSchema = z
  .object({
    refresh_token: z.string().min(1).max(256).openapi({ description: 'The refresh token issued with the session' }),
  })
  .strict()

export const UpdatePasswordSchema = z
  .object({
    password: z.string().min(8).max(72).openapi({ example: 'correct horse battery', minLength: 8 }),
  })
  .strict()

export const OAuthStartResponseSchema = z
  .object({
    authorize_url: z.string().url().openapi({
      description: 'The Supabase authorize URL to redirect the browser to',
      example: 'https://xxxx.supabase.co/auth/v1/authorize?provider=google&redirect_to=…',
    }),
  })
  .openapi('OAuthStart')

export const AuthUserSchema = z
  .object({
    id: UuidSchema,
    email: z.string().nullable().openapi({ example: 'alex@example.com' }),
    display_name: z.string().openapi({ example: 'Alex Chen', description: 'From the profiles table' }).nullable(),
    created_at: TimestampSchema,
  })
  .openapi('AuthUser')

export const SessionSchema = z
  .object({
    access_token: z.string().openapi({ description: 'Supabase JWT — send as Authorization: Bearer <token>' }),
    refresh_token: z.string().nullable(),
    expires_in: z.number().int().nullable(),
    token_type: z.string().nullable(),
    user: AuthUserSchema,
  })
  .openapi('Session')

// ---------------------------------------------------------------- notebooks
export const NotebookSchema = z
  .object({
    id: UuidSchema,
    owner_id: UuidSchema,
    title: z.string().openapi({ example: 'Morning Pages' }),
    group_id: UuidSchema.nullable().openapi({
      description: 'The group this notebook is shared with, or null when private',
      example: null,
    }),
    created_at: TimestampSchema,
    updated_at: TimestampSchema,
  })
  .openapi('Notebook')

export const CreateNotebookSchema = z
  .object({
    title: z.string().min(1).max(120).openapi({ example: 'Morning Pages' }),
  })
  .strict()

export const UpdateNotebookSchema = z
  .object({
    title: z.string().min(1).max(120).optional().openapi({ example: 'Morning Pages, volume 2' }),
    group_id: z.uuid().nullable().optional().openapi({
      description:
        'Link this notebook to a group you belong to (its uuid), or null to unlink. A notebook links to at most one group.',
      example: null,
    }),
  })
  .strict()

// ---------------------------------------------------------------- entries
export const EntrySchema = z
  .object({
    id: UuidSchema,
    notebook_id: UuidSchema,
    author_id: UuidSchema,
    title: z.string().openapi({ example: 'A slow morning' }),
    body: z.string().openapi({ example: 'Woke up early, the coffee was **excellent**…' }),
    mood: MoodSchema.nullable(),
    tags: TagsSchema,
    is_shared: z.boolean().openapi({
      description:
        'false opts this entry out of the notebook-level group sharing. Only meaningful once the notebook is linked to a group.',
    }),
    created_at: TimestampSchema,
    updated_at: TimestampSchema,
  })
  .openapi('Entry')

export const CreateEntrySchema = z
  .object({
    title: z.string().min(1).max(200).openapi({ example: 'A slow morning' }),
    body: z.string().max(100000).openapi({ example: 'Woke up early, the coffee was **excellent**…' }),
    mood: MoodSchema.optional().openapi({ example: 'good' }),
    tags: TagsSchema.optional().openapi({ example: ['morning', 'gratitude'] }),
    is_shared: z.boolean().optional().openapi({ example: true, description: 'Defaults to true' }),
  })
  .strict()

export const UpdateEntrySchema = z
  .object({
    title: z.string().min(1).max(200).optional(),
    body: z.string().max(100000).optional(),
    mood: MoodSchema.nullable().optional().openapi({ description: 'null clears the mood' }),
    tags: TagsSchema.optional(),
    is_shared: z.boolean().optional(),
  })
  .strict()

// ---------------------------------------------------------------- groups
export const GroupSchema = z
  .object({
    id: UuidSchema,
    owner_id: UuidSchema,
    name: z.string().openapi({ example: 'Family' }),
    created_at: TimestampSchema,
    auto_accept: z
      .boolean()
      .openapi({ description: 'Whether invite-link visitors join instantly or request approval' }),
    my_role: z.enum(['owner', 'member']).openapi({ description: 'Your role in this group' }),
    member_count: z.number().int().openapi({ example: 3 }),
  })
  .openapi('Group')

export const CreateGroupSchema = z
  .object({
    name: z.string().min(1).max(80).openapi({ example: 'Family' }),
  })
  .strict()

export const UpdateGroupSchema = z
  .object({
    name: z.string().min(1).max(80).optional().openapi({ example: 'Family & close friends' }),
    auto_accept: z.boolean().optional().openapi({
      example: false,
      description: 'When true, invite-link visitors join instantly; when false they file a join request for approval',
    }),
  })
  .strict()

export const GroupMemberSchema = z
  .object({
    user_id: UuidSchema,
    email: z.string().nullable().openapi({ example: 'sam@example.com' }),
    display_name: z.string().nullable().openapi({ example: 'Sam Rivera' }),
    role: z.enum(['owner', 'member']),
    joined_at: TimestampSchema,
  })
  .openapi('GroupMember')

// ---------------------------------------------------------------- invites (link-based)
export const InviteLinkSchema = z
  .object({
    url: z.string().nullable().openapi({
      example: '/invites/accept?token=…',
      description:
        'The shareable invite link. Only ever populated by the rotate response: only a hash is stored, so an existing link cannot be shown again.',
    }),
    has_link: z.boolean().openapi({
      description: 'Whether an active link exists. True while url is null means "active, but not recoverable"',
    }),
    expires_at: TimestampSchema.nullable().openapi({
      description: 'When the link stops working, or null when it never expires',
    }),
    auto_accept: z
      .boolean()
      .openapi({ description: 'Whether link visitors join instantly (true) or file a request (false)' }),
  })
  .openapi('InviteLink')

export const CreateInviteLinkSchema = z
  .object({
    expires_in_hours: z.coerce.number().int().min(1).max(720).nullable().optional().openapi({
      example: 168,
      description: 'How long the new link stays valid; null/omitted = never expires. Always rotates the token.',
    }),
  })
  .strict()

export const LinkInfoSchema = z
  .object({
    token: z.string().openapi({ example: '9f8e7d…' }),
    group_name: z.string().openapi({ example: 'Family' }),
    group_id: UuidSchema,
    auto_accept: z.boolean(),
    expires_at: TimestampSchema.nullable(),
    usable: z.boolean().openapi({ description: 'False when the link is revoked or past its expiry' }),
  })
  .openapi('LinkInfo')

export const JoinResultSchema = z
  .object({
    status: z.enum(['joined', 'requested', 'member', 'pending']).openapi({
      description:
        'joined = member now; requested = approval pending; member = already in; pending = request already open',
    }),
    group_id: UuidSchema,
    group_name: z.string(),
    message: z.string(),
  })
  .openapi('JoinResult')

export const JoinRequestSchema = z
  .object({
    id: UuidSchema,
    group_id: UuidSchema,
    user_id: UuidSchema,
    email: z.string().nullable().openapi({ example: 'sam@example.com' }),
    display_name: z.string().nullable().openapi({ example: 'Sam Rivera' }),
    status: z.enum(['pending', 'approved', 'denied']),
    created_at: TimestampSchema,
  })
  .openapi('JoinRequest')
