import { z } from '@hono/zod-openapi'

/**
 * Shared Zod schemas — single source of truth for request validation and
 * OpenAPI response documentation. Reusable on the client for form validation.
 */

// ---------------------------------------------------------------- primitives
export const UuidSchema = z.uuid().openapi({ example: '123e4567-e89b-12d3-a456-426614174000' })
export const TimestampSchema = z.string().openapi({ format: 'date-time', example: '2026-09-12T08:30:00.000Z' })

export const MoodSchema = z.enum(['great', 'good', 'okay', 'low', 'rough']).openapi({
  description: 'Mood rating: great 😄, good 🙂, okay 😐, low 🙁, rough 😣',
  example: 'good',
})

export const TagsSchema = z
  .array(z.string().min(1).max(40))
  .max(20)
  .openapi({ example: ['gratitude', 'work'], description: 'Free-text tags, per user' })

// ---------------------------------------------------------------- pagination
export const PageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1).openapi({ example: 1, description: '1-based page number' }),
  limit: z.coerce.number().int().min(1).max(100).default(20).openapi({ example: 20 }),
})

export function PaginatedSchema<T extends z.ZodType>(item: T) {
  return z.object({
    data: z.array(item),
    pagination: z.object({
      page: z.number().int().openapi({ example: 1 }),
      limit: z.number().int().openapi({ example: 20 }),
      total: z.number().int().openapi({ example: 42, description: 'Total rows matching the query' }),
    }),
  })
}

// ---------------------------------------------------------------- profiles
export const ProfileSchema = z
  .object({
    id: UuidSchema,
    display_name: z.string().openapi({ example: 'Alex Chen' }),
    email: z.string().openapi({ example: 'alex@example.com', description: 'From the auth user record' }),
    created_at: TimestampSchema,
  })
  .openapi('Profile')

export const UpdateProfileSchema = z
  .object({
    display_name: z.string().min(1).max(80).openapi({ example: 'Alex Chen' }),
  })
  .strict()

// ---------------------------------------------------------------- auth
export const SignUpSchema = z
  .object({
    email: z.email().openapi({ example: 'alex@example.com' }),
    password: z.string().min(8).max(72).openapi({ example: 'correct horse battery', minLength: 8 }),
    display_name: z.string().min(1).max(80).optional().openapi({ example: 'Alex Chen' }),
  })
  .strict()

export const LoginSchema = z
  .object({
    email: z.email().openapi({ example: 'alex@example.com' }),
    password: z.string().min(1).openapi({ example: 'correct horse battery' }),
  })
  .strict()

export const MagicLinkSchema = z
  .object({
    email: z.email().openapi({ example: 'alex@example.com' }),
    redirect_to: z.string().url().optional().openapi({ example: 'http://localhost:3000/auth/callback' }),
  })
  .strict()

export const OAuthStartSchema = z
  .object({
    provider: z
      .enum(['google'])
      .openapi({ example: 'google', description: 'OAuth provider enabled on this deployment' }),
    code_challenge: z.string().min(43).max(128).openapi({
      description: 'Base64url(SHA-256(code_verifier)) — PKCE S256 challenge generated by the client',
      example: 'dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk',
    }),
  })
  .strict()

export const OAuthCallbackSchema = z
  .object({
    auth_code: z
      .string()
      .min(1)
      .max(1024)
      .openapi({ description: 'The code Supabase appended to your redirect URL after the provider round-trip' }),
    code_verifier: z
      .string()
      .min(43)
      .max(128)
      .openapi({ description: 'The PKCE verifier the client stored when starting the flow' }),
  })
  .strict()

export const RefreshSchema = z
  .object({
    refresh_token: z.string().min(1).max(256).openapi({ description: 'The refresh token issued with the session' }),
  })
  .strict()

export const UpdatePasswordSchema = z
  .object({
    password: z.string().min(8).max(72).openapi({ example: 'correct horse battery', minLength: 8 }),
  })
  .strict()

// ---------------------------------------------------------------- encryption (E2EE)
// The server relays opaque blobs only — it cannot decrypt any of them.

export const PublishKeysSchema = z
  .object({
    salt: z.string().min(1).max(64).openapi({ description: 'PBKDF2 salt (base64, public by design)' }),
    iterations: z.coerce.number().int().min(100_000).max(2_000_000).openapi({ description: 'PBKDF2 round count' }),
    wrapped_dek: z.string().min(1).max(4096).openapi({ description: 'Data key sealed under the password-derived KEK' }),
    public_key: z
      .string()
      .min(1)
      .max(1024)
      .openapi({ description: 'ECDH P-256 public key (SPKI base64) for sealed boxes' }),
    wrapped_private_key: z
      .string()
      .min(1)
      .max(8192)
      .openapi({ description: 'Identity private key sealed under the DEK' }),
    /** Required when replacing existing material: proves the caller holds the current DEK. */
    previous_wrapped_dek: z.string().min(1).max(4096).optional(),
  })
  .strict()

export const KeyMaterialSchema = z
  .object({
    salt: z.string().nullable(),
    iterations: z.number().int().nullable(),
    wrapped_dek: z.string().nullable(),
    public_key: z.string().nullable(),
    wrapped_private_key: z.string().nullable(),
  })
  .openapi('KeyMaterial')

export const RegisterDeviceSchema = z
  .object({
    public_key: z.string().min(1).max(1024),
    label: z.string().max(120).optional(),
  })
  .strict()

export const DeviceView = z
  .object({
    id: UuidSchema,
    user_id: UuidSchema,
    public_key: z.string(),
    label: z.string().nullable(),
    created_at: TimestampSchema,
  })
  .openapi('Device')

export const DistributeGroupKeysSchema = z
  .object({
    generation: z.coerce
      .number()
      .int()
      .min(1)
      .max(1_000)
      .openapi({ description: 'Key generation; bumped on rotation' }),
    replace: z.boolean().optional().openapi({ description: 'Delete existing wraps first (owner only, for rotation)' }),
    wraps: z
      .array(
        z
          .object({
            device_id: UuidSchema,
            sealed_box: z.string().min(1).max(8192).openapi({ description: 'CEK sealed for this device' }),
          })
          .strict(),
      )
      .min(1)
      .max(200)
      .openapi({ description: 'One sealed box per device' }),
  })
  .strict()

export const GroupKeyWrapsView = z
  .object({
    wraps: z.array(
      z.object({
        device_id: UuidSchema,
        generation: z.number().int(),
        sealed_box: z.string(),
      }),
    ),
  })
  .openapi('GroupKeyWraps')

export const GroupDeviceView = z
  .object({
    user_id: UuidSchema,
    device_id: UuidSchema,
    public_key: z.string(),
    has_wrap: z.boolean(),
  })
  .openapi('GroupDevice')

export const EncryptMigrationSchema = z
  .object({
    entries: z
      .array(
        z
          .object({
            id: UuidSchema,
            title_cipher: z
              .string()
              .min(1)
              .max(2048)
              .openapi({ description: 'Sealed title (or legacy title when unencrypted)' }),
            body_cipher: z
              .string()
              .max(140_000)
              .openapi({ description: 'Sealed body (or legacy body when unencrypted)' }),
            author_wrap: z
              .string()
              .min(1)
              .max(8192)
              .openapi({ description: 'Content key sealed under the author\u2019s DEK' }),
            group_wrap: z
              .string()
              .min(1)
              .max(8192)
              .optional()
              .openapi({ description: 'Content key sealed under the group CEK (shared entries only)' }),
          })
          .strict(),
      )
      .min(1)
      .max(100)
      .openapi({ description: 'One batch of entries to flip to encrypted' }),
  })
  .strict()

export const EncryptMigrationResultSchema = z
  .object({
    migrated: z.number().int().openapi({ description: 'Rows flipped to encrypted this batch' }),
    remaining: z.number().int().openapi({ description: 'Unencrypted rows still to go' }),
  })
  .openapi('EncryptMigrationResult')

export const OAuthStartResponseSchema = z
  .object({
    authorize_url: z.string().url().openapi({
      description: 'The Supabase authorize URL to redirect the browser to',
      example: 'https://xxxx.supabase.co/auth/v1/authorize?provider=google&redirect_to=…',
    }),
  })
  .openapi('OAuthStart')

export const AuthUserSchema = z
  .object({
    id: UuidSchema,
    email: z.string().nullable().openapi({ example: 'alex@example.com' }),
    display_name: z.string().openapi({ example: 'Alex Chen', description: 'From the profiles table' }).nullable(),
    created_at: TimestampSchema,
  })
  .openapi('AuthUser')

export const SessionSchema = z
  .object({
    access_token: z.string().openapi({ description: 'Supabase JWT — send as Authorization: Bearer <token>' }),
    refresh_token: z.string().nullable(),
    expires_in: z.number().int().nullable(),
    token_type: z.string().nullable(),
    user: AuthUserSchema,
  })
  .openapi('Session')

// ---------------------------------------------------------------- notebooks
export const NotebookSchema = z
  .object({
    id: UuidSchema,
    owner_id: UuidSchema,
    title: z.string().openapi({ example: 'Morning Pages' }),
    group_id: UuidSchema.nullable().openapi({
      description: 'The group this notebook is shared with, or null when private',
      example: null,
    }),
    created_at: TimestampSchema,
    updated_at: TimestampSchema,
  })
  .openapi('Notebook')

export const CreateNotebookSchema = z
  .object({
    title: z.string().min(1).max(120).openapi({ example: 'Morning Pages' }),
  })
  .strict()

export const UpdateNotebookSchema = z
  .object({
    title: z.string().min(1).max(120).optional().openapi({ example: 'Morning Pages, volume 2' }),
    group_id: z.uuid().nullable().optional().openapi({
      description:
        'Link this notebook to a group you belong to (its uuid), or null to unlink. A notebook links to at most one group.',
      example: null,
    }),
  })
  .strict()

// ---------------------------------------------------------------- entries
export const EntrySchema = z
  .object({
    id: UuidSchema,
    notebook_id: UuidSchema,
    author_id: UuidSchema,
    title: z.string().openapi({ example: 'A slow morning' }),
    body: z.string().openapi({ example: 'Woke up early, the coffee was **excellent**…' }),
    mood: MoodSchema.nullable(),
    tags: TagsSchema,
    is_shared: z.boolean().openapi({
      description:
        'false opts this entry out of the notebook-level group sharing. Only meaningful once the notebook is linked to a group.',
    }),
    encrypted: z.boolean().openapi({ description: 'true = title and body are client-sealed ciphertext' }),
    created_at: TimestampSchema,
    updated_at: TimestampSchema,
  })
  .openapi('Entry')

export const CreateEntrySchema = z
  .object({
    title: z.string().min(1).max(2000).openapi({
      example: 'A slow morning',
      description: 'Plaintext title, or the sealed title envelope when encrypted=true',
    }),
    body: z.string().max(140000).openapi({
      example: 'Woke up early, the coffee was **excellent**…',
      description: 'Plaintext markdown, or the sealed body envelope when encrypted=true',
    }),
    mood: MoodSchema.optional().openapi({ example: 'good' }),
    tags: TagsSchema.optional().openapi({ example: ['morning', 'gratitude'] }),
    is_shared: z.boolean().optional().openapi({ example: true, description: 'Defaults to true' }),
    encrypted: z.boolean().optional().openapi({ example: true, description: 'Defaults to false (legacy plaintext)' }),
    key_wraps: z
      .array(
        z
          .object({
            scope: z.enum(['author', 'group']),
            wrapped_key: z
              .string()
              .min(1)
              .max(8192)
              .openapi({ description: 'Entry content key, sealed for the scope' }),
          })
          .strict(),
      )
      .max(2)
      .optional()
      .openapi({ description: 'Content-key wraps written alongside an encrypted entry' }),
  })
  .strict()

export const UpdateEntrySchema = z
  .object({
    title: z.string().min(1).max(2000).optional(),
    body: z.string().max(140000).optional(),
    mood: MoodSchema.nullable().optional().openapi({ description: 'null clears the mood' }),
    tags: TagsSchema.optional(),
    is_shared: z.boolean().optional(),
    encrypted: z.boolean().optional().openapi({ description: 'Flip ciphertext state alongside sealed title/body' }),
    key_wraps: z
      .array(
        z
          .object({
            scope: z.enum(['author', 'group']),
            wrapped_key: z.string().min(1).max(8192),
          })
          .strict(),
      )
      .max(2)
      .optional()
      .openapi({ description: 'Replace the entry\u2019s content-key wraps (used when toggling sharing)' }),
  })
  .strict()

// ---------------------------------------------------------------- groups
export const GroupSchema = z
  .object({
    id: UuidSchema,
    owner_id: UuidSchema,
    name: z.string().openapi({ example: 'Family' }),
    created_at: TimestampSchema,
    auto_accept: z
      .boolean()
      .openapi({ description: 'Whether invite-link visitors join instantly or request approval' }),
    my_role: z.enum(['owner', 'member']).openapi({ description: 'Your role in this group' }),
    member_count: z.number().int().openapi({ example: 3 }),
    webhook_url: z
      .string()
      .url()
      .nullable()
      .optional()
      .openapi({ example: 'https://discord.com/api/webhooks/123/xyz', description: 'Notification webhook URL' }),
  })
  .openapi('Group')

export const CreateGroupSchema = z
  .object({
    name: z.string().min(1).max(80).openapi({ example: 'Family' }),
  })
  .strict()

export const UpdateGroupSchema = z
  .object({
    name: z.string().min(1).max(80).optional().openapi({ example: 'Family & close friends' }),
    auto_accept: z.boolean().optional().openapi({
      example: false,
      description: 'When true, invite-link visitors join instantly; when false they file a join request for approval',
    }),
    webhook_url: z
      .union([z.string().url(), z.literal(''), z.null()])
      .optional()
      .transform((v) => (v === '' || v === undefined ? null : v))
      .refine((v: string | null) => v === null || /^https:\/\//i.test(v), {
        message: 'Webhook URLs must be https',
      })
      .openapi({
        example: 'https://discord.com/api/webhooks/123/xyz',
        description:
          'HTTPS webhook URL for notifications, or null/empty to disable. Private/internal hosts are rejected at send time.',
      }),
  })
  .strict()

export const GroupMemberSchema = z
  .object({
    user_id: UuidSchema,
    email: z.string().nullable().openapi({ example: 'sam@example.com' }),
    display_name: z.string().nullable().openapi({ example: 'Sam Rivera' }),
    role: z.enum(['owner', 'member']),
    joined_at: TimestampSchema,
  })
  .openapi('GroupMember')

// ---------------------------------------------------------------- invites (link-based)
export const InviteLinkSchema = z
  .object({
    url: z.string().nullable().openapi({
      example: '/invites/accept?token=…',
      description:
        'The shareable invite link. Only ever populated by the rotate response: only a hash is stored, so an existing link cannot be shown again.',
    }),
    has_link: z.boolean().openapi({
      description: 'Whether an active link exists. True while url is null means "active, but not recoverable"',
    }),
    expires_at: TimestampSchema.nullable().openapi({
      description: 'When the link stops working, or null when it never expires',
    }),
    auto_accept: z
      .boolean()
      .openapi({ description: 'Whether link visitors join instantly (true) or file a request (false)' }),
  })
  .openapi('InviteLink')

export const CreateInviteLinkSchema = z
  .object({
    expires_in_hours: z.coerce.number().int().min(1).max(720).nullable().optional().openapi({
      example: 168,
      description: 'How long the new link stays valid; null/omitted = never expires. Always rotates the token.',
    }),
  })
  .strict()

export const LinkInfoSchema = z
  .object({
    token: z.string().openapi({ example: '9f8e7d…' }),
    group_name: z.string().openapi({ example: 'Family' }),
    group_id: UuidSchema,
    auto_accept: z.boolean(),
    expires_at: TimestampSchema.nullable(),
    usable: z.boolean().openapi({ description: 'False when the link is revoked or past its expiry' }),
  })
  .openapi('LinkInfo')

export const JoinResultSchema = z
  .object({
    status: z.enum(['joined', 'requested', 'member', 'pending']).openapi({
      description:
        'joined = member now; requested = approval pending; member = already in; pending = request already open',
    }),
    group_id: UuidSchema,
    group_name: z.string(),
    message: z.string(),
  })
  .openapi('JoinResult')

export const JoinRequestSchema = z
  .object({
    id: UuidSchema,
    group_id: UuidSchema,
    user_id: UuidSchema,
    email: z.string().nullable().openapi({ example: 'sam@example.com' }),
    display_name: z.string().nullable().openapi({ example: 'Sam Rivera' }),
    status: z.enum(['pending', 'approved', 'denied']),
    created_at: TimestampSchema,
  })
  .openapi('JoinRequest')
